version: "3"

services:
  pgweb:
    image: sosedoff/pgweb
    container_name: cp-postgres-webview
    restart: unless-stopped
    links:
      - postgres:postgres
    depends_on:
      - postgres
    networks:
      - cpnetwork
    ports:
      - 8081:8081
    healthcheck:
      test: nc -vz 127.0.0.1 8081
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    container_name: cp-postgres
    image: postgres:15-alpine
    restart: unless-stopped
    user: ${POSTGRES_USER}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - cpnetwork
    volumes:
      - cp-postgres-data:/var/lib/postgresql/data/
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready",
          "-U",
          "${POSTGRES_USER}",
          "-d",
          "${POSTGRES_DB}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  nestjs:
    container_name: cp-nestjs
    build:
      context: .
      dockerfile: ./docker/${NODE_ENV}.Dockerfile
    # restart: unless-stopped
    env_file:
      - .env
    networks:
      - cpnetwork
    expose:
      - ${NESTJS_PORT}
    ports:
      - ${NESTJS_PORT}:${NESTJS_PORT}
      # The following port is for prisma studio
      - 5555:5555
    depends_on:
      - postgres
    volumes:
      - ./src:/usr/src/app/src
      - ./prisma:/usr/src/app/prisma

  btcpayserver:
    image: btcpayserver/btcpayserver:1.13.5
    container_name: cp-btcpayserver
    restart: unless-stopped
    environment:
      - NBITCOIN_NETWORK=mainnet
      - BTCPAY_HOST=https://cryptpulse.co
      - LETSENCRYPT_EMAIL=jean.paul.bassil@outlook.com
      - BTCPAYGEN_CRYPTO1=btc
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - btcpay_data:/data
    networks:
      - cpnetwork

volumes:
  cp-postgres-data:
  btcpay_data:

networks:
  cpnetwork:
